# This file contains instructions for the build server Travis
# The build is running on https://travis-ci.com/.
sudo: required
dist: trusty
language: node_js
node_js:
  - '10.16.0'
env:
  global:
    - secure: "OJtjcQ41494IeUQ7CpD1HfYgNJndcoloZL8zBIyP/N+Vy1c2u8qJ3gPRt5MJy2I/enzPMiMEsEHKgQA6rbcuMsYb3GR7X4tRHqXStLV0VcHGsGSo+hROvOp1bbqqYDZ8R2xoqJbSBu3elQrQmLrZH59rP1ovv8Vub7CPfYZXpHqFA4pBgNkQtCfZ7P54aJnwd4Ptm3ralTvfK3DswYYYbCPA4slKX/k5KtKUmT4oz4P6UtrcDghXrgOKLnKUmHIzv0wC/+sj+bEQjqW78pn3ICDzaoVfhSlI14W9vyfDmP5ue+86xa8xJrqUvhmMyhCW+4TTgHahafxN2CGcA9aVjoSg0oKPTT97WIR14OvfDDEUreTLoO4T9x3AUvm5m9WW8MBd14LQ3VvsIc4VTwnNAhN9afl3rqFoqH0ukX95abnm4xz8hir2KCmsExTD/d6L0hYPVtBf7UB93sYqIf7zaz+Lfxskc7AzOYcq5aOvinohnnDGS5VQlOLzkbbbVVbefTVc5DbNXdoN/YytMtQGnZ4pzNbYKtqmIxMTfpJucctUty5DqvPK9wLAEvY7+zUalr4GN5kFoIg1Hy6sbBRng7r5BoKcB6APbjZxG5qHCNGTm9ELmjzV0g1RmKU1uZARI/WfQJnLcazz8EAKRnjbFGgyTbqh6nTqOoH37rPe9LE=" # $GH_TOKEN
install:
  - npm install
jobs:
  include:
    - stage: "Lint stage"
      name: "lints demo app"
      script:
        - ng lint
    - stage: "Build stage"
      name: "builds demo app and deploys it to GitHub Pages if on master branch"
      script:
        - ng build --prod --base-href "/scion-workbench-demo/"
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GH_TOKEN
          local_dir: dist/scion-workbench-demo
          on:
            branch: master
